config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :reports, :contracts

  root to: 'user#user_home'
  get '/forgot_password', to: 'user#forgot_password'
  get '/edit_password', to: 'user#edit_password'
  get '/sign_up', to: 'user#register'
  get '/users/:email(.:format)', to: 'user#after_forgot_password'

  get '/monthly_sales', to: 'dashboard#monthly_sales'
  get '/report_sales', to: 'dashboard#report_sales'
  get '/manager', to: 'dashboard#manager'
  get '/overview_months', to: 'dashboard#overview_months'
  get '/overview_reports', to: 'dashboard#overview_reports'
  get '/logout', to: 'dashboard#logout'
  post '/manage_new_user', to: 'dashboard#manage_new_user'
end

app/controllers/account_manager/dashboard_controller.rb
module AccountManager
  class DashboardController < AccountManager::DealDataController
    before_action except: [:logout] do
      verify_authorization(AccountManager::DashboardController)
    end

    before_action only: %i[monthly_sales monthly_forecast report_am] do
      init_current_report(SIDES[0])
    end

    before_action :authenticate_user!
    skip_before_action :verify_authenticity_token

    def monthly_sales
      data = fetch_contract_by_report_id(@current_report.id)
      data.empty? ? default_contract : fetch_contract_data_points(data)

      @user = fetch_username_by_types(SIDES[0], SIDES[2])

      render_menu(SIDES[0])
    end

    def monthly_forecast
      data = fetch_deal_by_report_id(@current_report.id)
      data.empty? ? default_deal : fetch_deal_data_points(data)

      @user = fetch_username_by_types(SIDES[0], SIDES[2])

      render_menu(SIDES[0])
    end

    def report_am
      fetch_record_data_points

      render_menu(SIDES[0])
    end

    def overview_months_am
      search_overview_months(SIDES[0])

      render_menu(SIDES[0])
    end

    def overview_reports_am
      search_overview_reports(SIDES[0])

      render_menu(SIDES[0])
    end

    def logout
      sign_out_and_redirect(current_user)
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < MonthlyController
  before_action :init_view_data,
                only: %i[monthly_sales manager overview_reports
                         overview_months report_sales]
  before_action :init_manager_data, only: [:manager]

  before_action :authenticate_user!, only: [:manager]
  skip_before_action :verify_authenticity_token

  include GraphicHelper

  def monthly_sales
    init_month_year_list
    search_sales

    @contract = Contract.new
    @day_text = day_text_generator
    @users = fetch_username_by_priority

    @month = ''
    @year = ''
    init_month_year

    render_menu
  end

  def report_sales
    init_month_year_list
    search_recods

    @graphic_text = day_text_generator

    render_menu
  end

  def manager
    @user = User.new
    @new_users = fetch_user_by_priority(-1)

    render_menu
  end

  def overview_months
    search_overview_months
    init_overview_options_list

    @month_text = month_text_generator
    render_menu
  end

  def overview_reports
    search_overview_reports

    init_overview_options_list
    verify_options unless params[:report].nil?

    @month_text = month_text_generator
    render_menu
  end

  def logout
    sign_out_and_redirect(current_user)
  end

  def manage_new_user
    if @priority.nil?
      @user.destroy
    else
      @priority = 2 if @priority > 2
      @user.priority = @priority
      @user.save

      send_out_message(@user.email)
    end
    redirect_to controller: 'dashboard', action: 'manager',
                'report[year]' => fetch_last_year
  end

  private

  def send_out_message(email)
    zapper = ZapierRuby::Zapper.new(:email_zap)
    zapper.zap(json_maker(email, 'Account permission allowed',
                          'Your account have been aproved: ' +
                          ENV['link_to_root']))
  end

  def init_manager_data
    authorize! :manager, DashboardController
    year = params[:report].nil? ? params[:year] : params[:report][:year]

    @spreadsheets = fetch_reports_by_year(year)
    @unique_years = fetch_report_by_unique_years(year.to_i)
  rescue CanCan::AccessDenied
    redirect_to graphic_path
  end

  def init_view_data
    @report = Report.new
  end

  def render_menu
    render layout: 'menu'
  end
end

app/controllers/sales_representative/dashboard_controller.rb
module SalesRepresentative
  class DashboardController < SalesRepresentative::MeetingDataController
    before_action do
      verify_authorization(SalesRepresentative::DashboardController)
    end

    before_action only: %i[monthly_schedules report_sdr] do
      init_current_report(SIDES[1])
    end

    def monthly_schedules
      data = fetch_meeting_by_report_id(@current_report.id)
      data.empty? ? default_meeting : fetch_meeting_data_points(data)

      @users = fetch_username_by_types(SIDES[1], SIDES[0])

      render_menu(SIDES[1])
    end

    def report_sdr
      fetch_record_data_points

      render_menu(SIDES[1])
    end

    def overview_months_sdr
      search_overview_months(SIDES[1])

      render_menu(SIDES[1])
    end

    def overview_reports_sdr
      search_overview_reports(SIDES[1])

      render_menu(SIDES[1])
    end
  end
end

app/views/dashboard/manager.html.slim
head
  title Sales Up - Management
body
  .row
    .panel.panel-default
      h3.h3.form-group.text-center.panel-default.panel-heading
        = "Management"

      div.panel-default.panel-heading.form-inline
        h2.h2.font-thin.form-group Spreadsheet Manager
        = simple_form_for @report, method: :get, url: manager_path, html: { class: "form-group m-l-xl", id: "formSelectBoxYear" } do |f|
          = f.input :year, label: false, :collection => @unique_years, :prompt => "Year", input_html: { class: "form-control", id: "monthBox",  :onchange => "sendData('formSelectBoxYear', 1)"}

        button.btn.btn-primary.btn-addon.btn-lg.margin.form-group.m-l-md data-target="#exampleModal" data-toggle="modal" type="button"
          i.fa.fa-plus
          | Spreadsheet
        #exampleModal.modal.fade aria-hidden="true" aria-labelledby="exampleModalLabel" role="dialog" tabindex="-1"
          .modal-dialog role="document"
            .modal-content
              .modal-header.form-inline
                h3.h3.modal-title.form-group New Spreadsheet
                button.close.form-group aria-label="Close" data-dismiss="modal" type="button" onclick="cleanDataSpreadsheet('#{fetch_last_year}')"
                  span aria-hidden="true"
                  | &times;
              = simple_form_for @report, method: :post, url: reports_path, default: { input_html: { class: "form-control" } } do |f|
                .modal-body
                  .form-inline.m-b
                    h4.h4 Spreadsheet name
                    = f.input :report_name, label: false, input_html: { style: "width:450px;", placeholder: "New spreadsheet name", id: "report_name_n" }
                  .form-inline
                    .form-group
                      h4.h4 Goal
                      = f.input :goal, as: :float, label: false, input_html: { min: "0", value: "", placeholder: "10000", id: "goal_n" }
                    .form-group.m-l
                      h4.h4 Month
                      = f.input :month_numb, label: false, :collection => (1..12).map { |m| [ Date::MONTHNAMES[m], m] }, input_html: { id: "month_n" }, prompt: false
                    .form-group.m-l
                      h4.h4 Year
                      = f.input :year, as: :integer, label: false, input_html: { min: "2010", max: @unique_years[0], id: "year_n", style: "width:120px;", value: fetch_last_year }
                .modal-footer
                  = f.button :submit, "Save changes", class: "btn btn-primary"
                  = f.button :button, "Close", class: "btn btn-danger", :'data-dismiss' => "modal", :onclick => "cleanDataSpreadsheet('#{fetch_last_year}'')"

      table.table.table-bordered.table-hover.table-condensed.bg-white-only
        tbody
          tr style=("font-weight: bold;")
            td style="width:35%"  Spreadsheet Name
            td style="width:20%"  Goal
            td style="width:20%"  Month/Year
            td style="width:25%"  Options
          -for report in @spreadsheets
            tr
              td.v-middle
                label id="#{report.id}l_report_name" = report['report_name']
                input hidden="" type="text" style="width: 300px;" value="#{report['report_name']}" name="report_name" id="#{report.id}report_name"
              td.v-middle
                label id="#{report.id}l_goal" = "R" + number_to_currency(report['goal']).to_s
                input.numbers hidden="" type="text" value="#{report['goal']}" name="goal" id="#{report.id}goal"
              td.v-middle
                label id="#{report.id}l_month_year" = report['month'] + "/" + report['year'].to_s
                input.numbers hidden="" type="text" value="#{report['month_numb']}" name="month" id="#{report.id}month"
                input.numbers hidden="" type="text" value="#{report['year'].to_s}" name="year" id="#{report.id}year"
              td
                div.form-inline id="#{report.id}divR1"
                  = simple_form_for @report, method: :get, url: monthly_sales_path, html: { class: "form-group" } do |f|
                    = f.input :month, as: :hidden, input_html: { value: "#{report.month}" }
                    = f.input :year, as: :hidden, input_html: { value: "#{report.year}" }
                    = f.input :report_name, as: :hidden, input_html: { value: "g" }
                    = f.button :submit, "View", class: "btn btn-info m-l"

                  button.btn.btn-info.m-l id="#{report.id}editR" onclick="reportVisibility(#{report.id}, true);" Edit
                  = simple_form_for @report, method: :delete, url: reports_path+"/"+report.id.to_s, html: { class: "form-group", :onsubmit => "if(!validateMyForm()){event.preventDefault();}" } do |f|
                    = f.button :submit, "Delete", class: "btn btn-danger m-l"

                div.form-inline id="#{report.id}divR2" hidden=""
                  = simple_form_for @report, method: :put, url: reports_path+"/"+report.id.to_s, html: { class: "form-group", :onsubmit => "if(!validateMyForm()){event.preventDefault();}" } do |f|
                    = f.input :month_numb, as: :hidden, input_html: { value: "m", id: report.id.to_s+"month"+report.id.to_s }
                    = f.input :year, as: :hidden, input_html: { value: "y", id: report.id.to_s+"year"+report.id.to_s }
                    = f.input :report_name, as: :hidden, input_html: { value: "r", id: report.id.to_s+"report_name"+report.id.to_s }
                    = f.input :goal, as: :hidden, input_html: { value: "g", id: report.id.to_s+"goal"+report.id.to_s }
                    = f.button :submit, "Save", class: "btn btn-success m-l form-group", :onclick => "fillData(#{report.id}, 'report_name', 'goal', 'month', 'year')"
                  button.btn.btn-info.form-group.m-l id="#{report.id}cancelR" onclick="reportVisibility(#{report.id}, false);" Cancel

    .panel.panel-default
      div.panel-default.panel-heading.form-inline
        h2.h2.font-thin.form-group New Registered Users

      table.table.table-bordered.table-hover.table-condensed.bg-white-only
        tbody
          tr style=("font-weight: bold;")
            td style="width:35%"  Full name
            td style="width:20%"  Email
            td style="width:20%"  Permission
            td style="width:25%"  Options
          -for new_user in @new_users
            tr
              td.v-middle
                label id="#{new_user.id}full_name" = new_user.full_name
              td.v-middle
                label id="#{new_user.id}email" = new_user.email
              td.v-middle
                select.form-control style="font-size: 18px; height: auto;" id="#{new_user.id}permission"
                  option value="0" Spector
                  option value="1" Salesman
                  option value="2" Manager
              td
                div.form-inline
                  = simple_form_for @user, method: :post, url: manage_new_user_path, html: { class: "form-group", :onsubmit => "if(!validateMyForm()){event.preventDefault();}" } do |f|
                    = f.input :priority, as: :hidden, input_html: { value: "p", id: new_user.id.to_s+"permission"+new_user.id.to_s }
                    = f.input :id, as: :hidden, input_html: { value: new_user.id }
                    = f.button :submit, "Allow", class: "btn btn-success m-l", :onclick => "fillUserData(#{new_user.id}, 'yes')"
                    = f.button :submit, "Deny", class: "btn btn-danger m-l", :onclick => "fillUserData(#{new_user.id}, 'no')"

app/views/dashboard/monthly_sales.html.slim
head
  title Sales Up - Monthly Sales
body onload="generateGraphicPlot(#{@report_points}, #{@contract_points}, #{@day_text}, '#{@month}', '#{@year}')"
  .row
    .panel.panel-default style="margin-top: -30px;"
      .panel-heading
        h3.h3.form-group.text-center
          = "Monthly Sales"
        .form-inline
          h3.h3.form-group
            = "Name:"
          h3.h3.font-thin.form-group.m-l = @current_report.report_name
        .form-inline
          h3.h3.form-group
            = "Goal: "
          h3.h3.font-thin.form-group.m-l = "R" + number_to_currency(@current_report.goal).to_s

          - if can? :create, ContractsController
            div.form-group.m-l-xxl align="right"
              button.btn.btn-primary.btn-addon.btn-lg.margin data-target="#addModal" data-toggle="modal" type="button"
                i.fa.fa-plus
                | Contract

      #addModal.modal.fade aria-hidden="true" aria-labelledby="exampleModalLabel" role="dialog" tabindex="-1"
        .modal-dialog role="document"
          .modal-content
            .modal-header.form-inline
              h3.h3.modal-title.form-group New Contract
              button.close.form-group aria-label="Close" data-dismiss="modal" type="button" onclick="cleanDataContract()"
                span aria-hidden="true"
                | &times;
            = simple_form_for @contract, method: :post, url: contracts_path do |f|
              .modal-body
                .form-inline.m-b
                  .form-group
                    h4.h4 Store name
                    = f.input :store_name, label: false, id: "store_name", input_html: { style: "width:337px;", value: "", placeholder: "New spreadsheet name", class: "form-control" }
                .form-inline.m-b
                  .form-group
                    h4.h4 Value
                    = f.input :value, as: :float, label: false, id: "value", input_html: { style: "width:100px;", value: "", placeholder: "699", class: "form-control" }
                  .form-group.m-l
                    h4.h4 Month/Year
                    = f.input :report_id, label: false, id: "report", prompt: false, collection: @month_year_list.map { |report| [report.month+"/"+report.year.to_s, fetch_report(report.month, report.year).id] } , input_html: { class: "form-control" }
                  .form-group.m-l
                    h4.h4 Day
                    = f.input :day, as: :integer, label: false, id: "day", input_html: { style: "width:65px;", value: "", placeholder: "26", class: "form-control", min: "1", max: "31" }
                .form-inline
                  = f.input :user_id, as: :hidden, label: false, id: "user_id", input_html: { value: @users[0].id }
                  - if can? :manager, DashboardController
                    .checkbox
                      h4.h4 Salesman name
                      .radio.form-inline
                        label.h4.i-checks.m-r-md.form-group
                          input type="radio" id="username#{@users[0].id}" name="username" required="" value="#{@users[0].full_name}" checked=""
                          i
                          | #{@users[0].full_name}
                        -for i in 1..@users.length-1
                          -next if @users[i].priority == 3
                          label.h4.i-checks.m-r-md.form-group
                            input type="radio" name="username" value="#{@users[i].full_name}" id="username#{@users[i].id}"
                            i
                            | #{@users[i].full_name}
                  -else
                    .checkbox
                      h4.h4 Salesman name
                      .radio.form-inline
                        label.h4.i-checks.m-r-md.form-group
                          input type="radio" id="username" name="username" required="" value="#{current_user.full_name}" checked=""
                          i
                          | #{current_user.full_name}
              .modal-footer
                = f.button :submit, "Save changes", class: "btn btn-primary"
                = f.button :button, "Close", class: "btn btn-danger", :'data-dismiss' => "modal", :onclick => "cleanDataContract()"

      .panel-body style="font-size: 25px; font-weight: bold;"
        div id="placeholderG" style="height:450px;width:1250px;"

      div.panel-default style="margin-top: 15px;"
        table.table ui-jq="footable"
          thead
            tr
              th Day
              th Weekdays
              th Daily Goal
              th Contract Sum
              th Store Name
              th Contract Values
              th Salesman Name
              - if can? :manage, ContractsController
                th Options
          tbody
            - @report_data.each_with_index do |data, i|
              tr
                td = data[0]
                td = data[1]
                td = "R" + number_to_currency(data[2]).to_s
                td = "R" + number_to_currency(data[3]).to_s
                td id="tdStore#{i}" = data[4]
                td = "R" + number_to_currency(data[5]).to_s
                td id="tdSalesman#{i}" = data[6]
                - if data[4][0] == "1"
                  script type="text/javascript" highLight("#{data[4]}", "#{data[6]}", "tdStore#{i}", "tdSalesman#{i}");
                td
                  - if can?(:update, ContractsController) && data[4] != '-'
                    button.btn.btn-info data-target="#editModal#{data[0]}" data-toggle="modal" type="button" id="#{data[0]}edit" Edit

                    .modal.fade id="editModal#{data[0]}" aria-hidden="true" aria-labelledby="exampleModalLabel" role="dialog" tabindex="-1"
                      .modal-dialog role="document" style="width: 65%;"
                        .modal-content
                          .modal-header.form-inline
                            h3.h3.modal-title.form-group Edit Contract
                            button.close.form-group aria-label="Close" data-dismiss="modal" type="button" onclick="cleanDataContract()"
                              span aria-hidden="true"
                              | &times;
                          .modal-body
                            table.table.table-bordered.table-hover.table-condensed.bg-white-only style="width: 905px;"
                              thead
                                tr style=("font-weight: bold;")
                                  td style="width:5%"  Day
                                  td style="width:10%"  Store Name
                                  td style="width:15%"  Value
                                  td style="width:25%"  Salesman Name
                                  td style="width:20%"  Options
                              tbody
                                - fetch_contracts_by_day_report_id(data[0], @current_report).each do |contract|
                                  tr
                                    td.v-middle
                                      input style='width: 55px;' type='number' value="#{contract.day}" id="#{contract.id}day"
                                    td.v-middle
                                      input style='width: 190px;' type='text' value="#{contract.store_name}" id="#{contract.id}store_name"
                                    td.v-middle
                                      input style='width: 80px;' type='decimal' value="#{contract.value}" id="#{contract.id}value"
                                    td.v-middle
                                      select id="#{contract.id}user_id"
                                        option value="#{contract.user_id}" = fetch_username_by_id(contract.user_id)
                                        - @users.each do |user|
                                          - next if user.id == contract.user_id
                                          option value="#{user.id}" = user.full_name
                                    td.v-middle.form-inline
                                      = simple_form_for @contract, method: :put, url: contracts_path+"/"+contract.id.to_s, html: { class: "form-group" }, onsubmit: "if(!validateMyForm()){event.preventDefault();}" do |f|
                                        = f.input :day, as: :hidden, input_html: { value: "m", id: contract.id.to_s+"day"+contract.id.to_s }
                                        = f.input :store_name, as: :hidden, input_html: { value: "m", id: contract.id.to_s+"store_name"+contract.id.to_s }
                                        = f.input :value, as: :hidden, input_html: { value: "m", id: contract.id.to_s+"value"+contract.id.to_s }
                                        = f.input :user_id, as: :hidden, input_html: { value: "m", id: contract.id.to_s+"user_id"+contract.id.to_s }
                                        = f.input :report_id, as: :hidden, input_html: { value: @current_report.id }
                                        = f.button :submit, "Save", class: "btn btn-success form-group", :onclick => "fillData(#{contract.id}, 'day', 'store_name', 'value', 'user_id')"
                                      - if can?(:manage, ContractsController)
                                        = simple_form_for @contract, method: :delete, url: "/contracts/"+contract.id.to_s, html: { class: "form-group", :onsubmit => "if(!validateMyForm()){event.preventDefault();}" } do |f|
                                          = f.button :submit, "Delete", class: "btn btn-danger m-l form-group"

                          .modal-footer
                            button.btn.btn-info data-dismiss="modal" type="button" onclick="cleanDataContract()" Back

app/views/dashboard/overview.html.slim
head
  title Sales Up - Overview
body onload="generateOverviewPlot(#{@goal_points}, #{@sum_points}, #{@month_text})"
  div style="margin-top: -30px;"
    .row
      .panel.panel-default
        .panel-heading
          .form-inline
            = simple_form_for @report, method: :get, url: "/overview", html: { class: "form-group" } do |f|
              h3.h3.form-group.m-r
                = "Between: "
                - @first_list.delete(@last_list[0])
                = f.input :month, label: false, :collection => @first_list, :prompt => false, input_html: { class: "form-control", id: "monthBox", align: "central"}

              h3.h3.form-group.m-r
                = "And: "
                - @last_list.delete(@first_list[0])
                = f.input :year, label: false, :collection => @last_list, :prompt => false, input_html: { class: "form-control", id: "monthBox", align: "central"}

              = f.button :submit, "Search", class: "btn btn-primary btn-addon btn-lg margin m-l"
        .panel-body style="font-size: 25px; font-weight: bold;"
          div id="placeholderO" style="height:450px;width:1250px;"
          = simple_form_for @report, method: :get, url: "/monthly_sales", html: { class: "form-group", id: "formSearch" } do |f|
            = f.input :month, as: :hidden, input_html: { id: "monthSearch", value: "t"}
            = f.input :year, as: :hidden, input_html: { id: "yearSearch", value: "y"}

app/views/dashboard/overview_months.html.slim
head
  title Sales Up - Overview Month
body onload="generateOverviewPlot(#{@goal_points}, #{@sum_points}, #{@month_text})"
  div style="margin-top: -30px;"
    .row
      .panel.panel-default
        .panel-heading
          h3.h3.form-group.text-center.m-b
            = "Overview Month"
          .form-inline
            = simple_form_for @report, method: :get, url: overview_months_path, html: { class: "form-group" } do |f|
              h3.h3.form-group.m-r
                = "Between: "
                - @first_list.delete(@last_list[0])
                = f.input :month, label: false, :collection => @first_list, :prompt => false, input_html: { class: "form-control", id: "monthBox", align: "central"}

              h3.h3.form-group.m-r
                = "And: "
                - @last_list.delete(@first_list[0])
                = f.input :year, label: false, :collection => @last_list, :prompt => false, input_html: { class: "form-control", id: "monthBox", align: "central"}

              = f.button :submit, "Search", class: "btn btn-primary btn-addon btn-lg margin m-l"

        .panel-body style="font-size: 25px; font-weight: bold;"
          div id="placeholderO" style="height:450px;width:1250px;"
          = simple_form_for @report, method: :get, url: monthly_sales_path, html: { class: "form-group", id: "formSearch" } do |f|
            = f.input :month, as: :hidden, input_html: { id: "monthSearch", value: "t"}
            = f.input :year, as: :hidden, input_html: { id: "yearSearch", value: "y"}

app/views/dashboard/overview_reports.html.slim
head
  title Sales Up - Overview Report
body onload="generateOverviewRecordPlot(#{@salesman_points}, #{@usernames}, #{@month_text}, '#{@simbol}')"
  div style="margin-top: -30px;"
    .row
      .panel.panel-default
        .panel-heading
          h3.h3.form-group.text-center.m-b
            = "Overview Report"
          .form-inline
            = simple_form_for @report, method: :get, url: overview_reports_path, html: { class: "form-group" } do |f|
              h3.h3.form-group.m-r
                = "Between: "
                - @first_list.delete(@last_list[0])
                = f.input :month, label: false, :collection => @first_list, :prompt => false, input_html: { class: "form-control", id: "monthBox", align: "central"}

              h3.h3.form-group.m-r
                = "And: "
                - @last_list.delete(@first_list[0])
                = f.input :year, label: false, :collection => @last_list, :prompt => false, input_html: { class: "form-control", id: "monthBox", align: "central"}

              h3.h3.form-group.m-r
                = "Compare: "
                = f.input :report_name, label: false, :collection => @user_options, :prompt => false, input_html: { class: "form-control", id: "monthBox" }

              h3.h3.form-group.m-r
                = "With: "
                = f.input :goal, label: false, :collection => @filter_options, :prompt => false, input_html: { class: "form-control", id: "monthBox" }

              = f.button :submit, "Search", class: "btn btn-primary btn-addon btn-lg margin m-l"

        .panel-body style="font-size: 25px; font-weight: bold;"
          div id="placeholderOR" style="height:450px;width:1250px;"