config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :reports, :contracts

  root to: 'user#user_home'
  get '/forgot_password', to: 'user#forgot_password'
  get '/edit_password', to: 'user#edit_password'
  get '/sign_up', to: 'user#register'
  get '/users/:email(.:format)', to: 'user#after_forgot_password'

  get '/monthly_sales', to: 'dashboard#monthly_sales'
  get '/report_sales', to: 'dashboard#report_sales'
  get '/manager', to: 'dashboard#manager'
  get '/overview_months', to: 'dashboard#overview_months'
  get '/overview_reports', to: 'dashboard#overview_reports'
  get '/logout', to: 'dashboard#logout'
  post '/manage_new_user', to: 'dashboard#manage_new_user'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # attr_accessor :login

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def overall_manager?
    area == 'gg'
  end

  def sales?
    area == 'sales'
  end

  def admin?
    sub_area == 'admin'
  end

  def am?
    sub_area == 'am'
  end

  def sdr?
    sub_area == 'sdr'
  end

  def spectator?
    sub_area == 'spec'
  end

  def fn?
    sub_area == 'fn'
  end

  def ra?
    sub_area == 'ra'
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :verify_user_status
  before_action :generate_token, only: [:after_forgot_password]
  layout 'main'

  def user_home; end

  def forgot_password; end

  def create_schedule
    create_schedule_helper

    redirect_to root_path
  end

  def create_contract
    create_contract_helper

    redirect_to root_path
  end

  def create_deal
    create_deal_helper

    redirect_to root_path
  end

  def destroy_deal
    fetch_deal_by_client(params[:client_name]).destroy

    redirect_to root_path
  end

  def edit_password
    redirect_to root_path unless fetch_token_usage(params[:token])
  end

  def root_without_locale
    redirect_to root_path(locale: :pt)
  end

  def after_forgot_password
    zapper = ZapierRuby::Zapper.new(:email_zap)
    result = if zapper.zap(
      json_maker(params[:user][:email], t('home.zapier-content'), @link)
    )
               t('home.zapier-success')
             else
               t('home.zapier-invalid')
             end

    redirect_to root_path, notice: result
  end

  private

  def generate_token
    token = SecureRandom.base58(24)
    user_email = params[:user][:email]

    save_token(fetch_user_by_email(user_email).id, token)
    @link = ENV['link_to_root'] + edit_password_path +
            '?token=' + token + '&email=' + @user_email
  end

  def save_token(id, token)
    TokenPassword.new(token: token, used: 'no', user_id: id).save
  end

  def verify_user_status
    redirect_to overview_months_am_path(locale: :pt) if user_signed_in?
  end
end

app/views/user/_resources.erb
<meta name="description" content="app, web app, responsive, responsive layout, admin, admin panel, admin dashboard, flat, flat ui, ui kit, AngularJS, ui route, charts, widgets, components" />

<link rel="stylesheet" href="/assets/animate.css" type="text/css" />
<link rel="stylesheet" href="/assets/font-awesome.min.css" type="text/css" />
<link rel="stylesheet" href="/assets/simple-line-icons.css" type="text/css" />
<link rel="stylesheet" href="/assets/bootstrap.css" type="text/css" />

<link rel="stylesheet" href="/assets/font.css" type="text/css" />
<link rel="stylesheet" href="/assets/app.css" type="text/css" />

<div class="text-center">
  <a href="http://site.trustvox.com.br/" ><img src="/assets/img/trustvox-login-logo.png"/></a>
  <h1>Sales Up</h1>
  <h4>Business Performance Manager</h4>
</div>

<script src="/assets/jquery.js"></script>
<script src="/assets/bootstrap.js"></script>
<script src="/assets/ui-load.js"></script>
<script src="/assets/ui-jp.config.js"></script>
<script src="/assets/ui-jp.js"></script>
<script src="/assets/ui-nav.js"></script>
<script src="/assets/ui-toggle.js"></script>
<script src="/assets/ui-client.js"></script>

app/views/user/edit_password.html.slim
.wrapper.text-center
  strong Enter your new password
= simple_form_for @user, method: :post, url: user_registration_path, html: { onsubmit: "if(!verifyPassword()){event.preventDefault();}" } do |f|
  .text-danger.text-center id="alertRegister"
    - unless alert.nil?
      - alert.each do |error|
        h4 = error
  .list-group.list-group-sm
    .list-group-item
      = f.input :password, as: :password, label: false,input_html: { placeholder:"Password", class: "form-control no-border" }, wrapper: false
      = f.input :email, as: :hidden, input_html: { value: params[:email] }
      = f.input :full_name, as: :hidden, input_html: { value: "edit" }
    .list-group-item
      = f.input :confirm_password, as: :password, label: false,input_html: { placeholder:"Confirm Password", class: "form-control no-border" }, wrapper: false
  = f.button :submit, "Send", class: "btn btn-lg btn-primary btn-block"

app/views/user/forgot_password.html.slim
.wrapper.text-center
  strong Enter your email to reset your password
= simple_form_for @user, method: :get, url: user_registration_path+"/:email" do |f|
  .list-group.list-group-sm
    .list-group-item
      = f.input :email, as: :email, label: false, input_html: { class: "form-control no-border", placeholder:"Email" }, wrapper: false
  = f.button :submit, "Send", class: "btn btn-lg btn-primary btn-block"
.text-center.m-t.m-b
  = link_to 'I remember my password', root_path

app/views/user/home.html.slim
html
  head
    meta charset="utf-8" /
    title Sales Up - Login

    meta content="app, web app, responsive, responsive layout, admin, admin panel, admin dashboard, flat, flat ui, ui kit, AngularJS, ui route, charts, widgets, components" name="description" /

    = stylesheet_link_tag 'animate', 'font-awesome.min', 'simple-line-icons', 'bootstrap', 'font', 'app'
  body
    .app.app-header-fixed
      .container.w-xxl.w-auto-xs ng-controller="SigninFormController" ng-init=("app.settings.container = false;") 

        .m-b-lg
        .text-center
		  a href="http://site.trustvox.com.br/" 
		    img src="/assets/img/trustvox-login-logo.png" /
		  h1 Sales Up
		  h4 Business Performance Manager

          = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
            .wrapper.text-center
              strong Please, fill in all the data below
              h4.text-danger = alert
            .list-group.list-group-sm
              .list-group-item
                = f.email_field :email, autocomplete: "email", placeholder:"Email", required:"", :class => "form-control no-border"
              .list-group-item
                = f.password_field :password, placeholder:"Password", required:"", :class => "form-control no-border"
            = f.submit "Log in", :class => "btn btn-lg btn-primary btn-block"
            .text-center.m-t.m-b
              = link_to 'Forgot your password?', forgot_password_path
      h1 = @teste
 

app/views/user/index.html.slim
html
  head
    meta charset="utf-8" /
    title Sales Up - Login

    meta content="app, web app, responsive, responsive layout, admin, admin panel, admin dashboard, flat, flat ui, ui kit, AngularJS, ui route, charts, widgets, components" name="description" /

    = stylesheet_link_tag 'animate', 'font-awesome.min', 'simple-line-icons', 'bootstrap', 'font', 'app'
  body
    .app.app-header-fixed
      .container.w-xxl.w-auto-xs ng-controller="SigninFormController" ng-init=("app.settings.container = false;") 

        .m-b-lg
        .text-center
		  a href="http://site.trustvox.com.br/" 
		    img src="/assets/img/trustvox-login-logo.png" /
		  h1 Sales Up
		  h4 Business Performance Manager

          form.form-validation name="form" action="/graphic"
            .wrapper.text-center
              strong Please, fill in all the data below
            .list-group.list-group-sm
              .list-group-item
                input.form-control.no-border ng-model="user.email" placeholder="Email" required="" type="email" /
              .list-group-item
                input.form-control.no-border ng-model="user.password" placeholder="Password" required="" type="password" /

            button.btn.btn-lg.btn-primary.btn-block ng-click="login()" ng-disabled="form.$invalid" type="submit"  Log in
            .text-center.m-t.m-b
              = link_to 'Forgot your password?', forgot_password_path

app/views/user/register.html.slim
= simple_form_for @user, method: :post, url: user_registration_path, html: { onsubmit: "if(!verifyPassword()){event.preventDefault();}" } do |f|
  .text-center.m-t-md
    h3.text-center Sign Up
    strong Please, fill in all the data below
    .text-danger id="alertRegister"
      - unless alert.nil?
        - alert.each do |error|
          h4 = error
  .list-group.list-group-sm
    .list-group-item
      = f.input :full_name, label: false, input_html: { placeholder:"User name", class: "form-control no-border" }, wrapper: false
    .list-group-item
      = f.input :email, as: :email, label: false,input_html: { class: "form-control no-border", placeholder:"Email" }, wrapper: false
    .list-group-item
      = f.input :password, as: :password, label: false,input_html: { placeholder:"Password", class: "form-control no-border" }, wrapper: false
    .list-group-item
      = f.input :confirm_password, as: :password, label: false,input_html: { placeholder:"Confirm Password", class: "form-control no-border" }, wrapper: false
  = f.button :submit, "Sign Up", class: "btn btn-lg btn-primary btn-block"
= link_to root_path
  h5.text-center Already have an account

app/views/user/user_home.html.slim
= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
  .text-center.m-t-lg
    h3.text-center = t('home.signin.title')
    strong = t('home.signin.request')
    h4.text-danger = alert
    h4.text-success = notice
  .list-group.list-group-sm
    .list-group-item
      = f.email_field :email, autocomplete: "email", placeholder:"Email", required:"", :class => "form-control no-border"
    .list-group-item
      = f.password_field :password, placeholder: t('home.password.placeholder'), required:"", :class => "form-control no-border"
  = f.submit t('home.signin.button'), :class => "btn btn-lg btn-primary btn-block"
.text-center.m-t-sm.m-b
  = link_to t('home.password.button'), forgot_password_path