config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :reports, :contracts

  root to: 'user#user_home'
  get '/forgot_password', to: 'user#forgot_password'
  get '/edit_password', to: 'user#edit_password'
  get '/sign_up', to: 'user#register'
  get '/users/:email(.:format)', to: 'user#after_forgot_password'

  get '/monthly_sales', to: 'dashboard#monthly_sales'
  get '/report_sales', to: 'dashboard#report_sales'
  get '/manager', to: 'dashboard#manager'
  get '/overview_months', to: 'dashboard#overview_months'
  get '/overview_reports', to: 'dashboard#overview_reports'
  get '/logout', to: 'dashboard#logout'
  post '/manage_new_user', to: 'dashboard#manage_new_user'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalesUp</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/main.html.slim
html
  head
    meta charset="utf-8" /
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app.app-header-fixed
      .container.w-xxl.w-auto-xs
        .m-b-lg
        .text-center
          = link_to(image_tag("Logotipo-RATrustvox.png"), "http://site.trustvox.com.br/")
          h1 = t('home.title')
          h4 = t('home.sub')
        = yield

app/views/layouts/menu.html.slim
html
  head
    meta charset="utf-8" /
    = stylesheet_link_tag "application", media: 'all'
    = javascript_include_tag "application", media: 'all'
  body
    .app onmousemove="verifyMousePosition(event)"
      #content role="main"
        .app-content-body
          - types = [[t('menu.sales_side'), t('menu.am_side'), t('menu.sdr_side')]]
          - links = [monthly_sales_path, monthly_schedules_path]
          .sidenav.bg-black#mySidenav
            nav.navi style="position: absolute; top: 0px;"
              - types.each_with_index do |list, i|
                ul.nav
                  li ui-sref-active="active"
                    a style="width: 200px; height: 50px"
                      i.glyphicon.glyphicon-calendar.icon.text-info-dker#icons
                      span.font-bold.icons-text = list[0]
                  - list.each_with_index do |data, i|
                    - next if i == 0
                    li ui-sref-active="active" style="left: 30px"
                      a style="width: 200px; height: 50px" onclick="redirectPage('#{("form-" + i.to_s)}')"
                        i.glyphicon.glyphicon-calendar.icon.text-info-dker#icons
                        = simple_form_for Report.new, method: :get, url: links[i-1], html: { id: ("form-" + i.to_s) } do |f|
                          span.font-bold.icons-text = data

          .form-inline.row.menu.panel.panel-default
            .form-group#menu-logo
              .form-group
                button.btn.btn-primary.btn-addon.btn-lg.btn-dark.btn-size style="font-size:22px; position: relative; left: -20px; width: 55px;" onmouseover="openNav()" &#9776;
              .form-group
                = link_to(image_tag("trustvox-menu-logo.png"), @current_user.sdr? ? monthly_schedules_path : monthly_sales_path)
              .form-group.margin
                h3.h3 = @page_title[1]
                h2.font-thin.h2 = @page_title[0]
            = render partial: @partial_path

            .form-group#menu-options
              - if can? :manager, Admin::ManagerController
                - if current_page?(controller: '/admin/manager', action: 'manager_settings')
                  button.btn.btn-primary.btn-addon.btn-info.btn-lg.disabled.margin = t('menu.button.settings')
                - else
                  = simple_form_for Report.new, method: :get, url: manager_path, html: { class: "form-group" } do |f|
                    = f.input :side, as: :hidden, input_html: { value: @page_title[2] }
                    = f.button :submit, t('menu.button.settings'), class: "btn btn-primary btn-addon btn-lg margin"

              = simple_form_for Report.new, method: :get, url: logout_path, html: { class: "form-group m-l-xxl" } do |f|
                = f.button :submit, t('menu.button.logout'), class: "btn btn-primary btn-addon btn-lg btn-dark btn-size"
          = yield